// ─── Poliklinik bazlı ilaç listesi ───────────────────────────────────────────
// Her polikliniğe 10 gerçek ilaç ismi

export const POLIKLINIK_ILACLARI = {
    "Kardiyoloji": [
        { ad: "Coraspin 100 mg", form: "Tablet", aciklama: "Antiplatelet - günde 1" },
        { ad: "Beloc Zok 50 mg", form: "Tablet", aciklama: "Beta bloker - sabah/akşam" },
        { ad: "Norvasc 5 mg", form: "Tablet", aciklama: "Kalsiyum kanal blokeri - günde 1" },
        { ad: "Lisinopril 10 mg", form: "Tablet", aciklama: "ACE inhibitörü - günde 1" },
        { ad: "Crestor 10 mg", form: "Tablet", aciklama: "Statin - gece 1" },
        { ad: "Lasix 40 mg", form: "Tablet", aciklama: "Diüretik - sabah 1" },
        { ad: "Aldactone 25 mg", form: "Tablet", aciklama: "Aldosteron antagonisti" },
        { ad: "Xarelto 20 mg", form: "Tablet", aciklama: "Antikoagülan - akşam yemekle" },
        { ad: "Nitrogliserin Spray", form: "Sprey", aciklama: "Anjina krizinde gerektiğinde" },
        { ad: "Digoxin 0.25 mg", form: "Tablet", aciklama: "Kalp glikozidi - günde 1" },
    ],
    "Dahiliye (İç Hastalıkları)": [
        { ad: "Glucophage 1000 mg", form: "Tablet", aciklama: "Metformin - yemekle günde 2" },
        { ad: "Levotiron 50 mcg", form: "Tablet", aciklama: "Tiroid hormonu - aç karnına" },
        { ad: "Omeprazol 20 mg", form: "Kapsül", aciklama: "Proton pompası - aç karnına" },
        { ad: "Demir Sülfat 325 mg", form: "Tablet", aciklama: "Demir takviyesi - günde 1" },
        { ad: "B12 Vitamini 1000 mcg", form: "Ampul", aciklama: "IM enjeksiyon - haftada 1" },
        { ad: "D Vitamini 50000 IU", form: "Kapsül", aciklama: "Haftada 1 - 8 hafta" },
        { ad: "Folik Asit 5 mg", form: "Tablet", aciklama: "Günde 1" },
        { ad: "Metilprednizolon 16 mg", form: "Tablet", aciklama: "Kortikosteroid - sabah" },
        { ad: "Allopurinol 300 mg", form: "Tablet", aciklama: "Gut tedavisi - günde 1" },
        { ad: "Colchicine 0.5 mg", form: "Tablet", aciklama: "Gut atağı - günde 2" },
    ],
    "Göz Hastalıkları": [
        { ad: "Refresh Tears", form: "Damla", aciklama: "Yapay gözyaşı - günde 4x" },
        { ad: "Vigamox Göz Damlası", form: "Damla", aciklama: "Antibiyotik - günde 3x" },
        { ad: "Tobradex Göz Damlası", form: "Damla", aciklama: "Antibiyotik+steroid - günde 4x" },
        { ad: "Lumigan 0.01%", form: "Damla", aciklama: "Glokom - geceleri 1 damla" },
        { ad: "Xalatan 0.005%", form: "Damla", aciklama: "Glokom - gece 1 damla" },
        { ad: "Maxidex Göz Damlası", form: "Damla", aciklama: "Steroid - günde 4x" },
        { ad: "Acyclovir Göz Merhemi", form: "Merhem", aciklama: "Herpetik keratit - günde 5x" },
        { ad: "Timolol 0.5%", form: "Damla", aciklama: "Glokom - sabah/akşam" },
        { ad: "Ozurdex İmplant", form: "İmplant", aciklama: "Deksametazon - uzman uygular" },
        { ad: "Lutein + Zeaksantin", form: "Kapsül", aciklama: "Maküla desteği - günde 1" },
    ],
    "Kulak Burun Boğaz": [
        { ad: "Augmentin 1000 mg", form: "Tablet", aciklama: "Antibiyotik - 12 saatte 1" },
        { ad: "Nasonex Sprey", form: "Sprey", aciklama: "Nazal steroid - sabah 2 puf" },
        { ad: "Telfast 120 mg", form: "Tablet", aciklama: "Antihistaminik - günde 1" },
        { ad: "Vibrocil Damla", form: "Damla", aciklama: "Nazal dekonjestan - günde 3x" },
        { ad: "Otipax Kulak Damlası", form: "Damla", aciklama: "Otit ağrısı - günde 3x" },
        { ad: "Ciprodex Kulak Damlası", form: "Damla", aciklama: "Antibiyotik kulak - günde 2x" },
        { ad: "Rhinocort Sprey", form: "Sprey", aciklama: "Nazal steroid - günde 1" },
        { ad: "Fexofenadine 180 mg", form: "Tablet", aciklama: "Alerjik rinit - günde 1" },
        { ad: "Erdostein 300 mg", form: "Kapsül", aciklama: "Mükolotik - günde 2" },
        { ad: "Bactroban Nazal Pomad", form: "Pomad", aciklama: "Nazal antibiyotik - günde 3x" },
    ],
    "Ortopedi": [
        { ad: "Voltaren 75 mg", form: "Tablet", aciklama: "NSAID - yemekle günde 2" },
        { ad: "Arcoxia 90 mg", form: "Tablet", aciklama: "COX-2 inhibitör - günde 1" },
        { ad: "Muscoril 4 mg", form: "Kapsül", aciklama: "Kas gevşetici - günde 3" },
        { ad: "Calcium + D3", form: "Tablet", aciklama: "Kemik desteği - günde 1" },
        { ad: "Calcitonin Sprey", form: "Sprey", aciklama: "Osteoporoz - günde 1 puf" },
        { ad: "Fosamax 70 mg", form: "Tablet", aciklama: "Bifosfonat - haftada 1 aç" },
        { ad: "Prolia 60 mg", form: "Enjeksiyon", aciklama: "6 ayda 1 SC enjeksiyon" },
        { ad: "Voltaren Jel %1", form: "Jel", aciklama: "Lokal NSAID - günde 3x" },
        { ad: "Neurontin 300 mg", form: "Kapsül", aciklama: "Nöropatik ağrı - günde 3" },
        { ad: "Tramadol 50 mg", form: "Kapsül", aciklama: "Opioid analjezik - gerektiğinde" },
    ],
    "Kadın Doğum": [
        { ad: "Folic Asit 5 mg", form: "Tablet", aciklama: "Gebelik öncesi/sırası - günde 1" },
        { ad: "Progestan 200 mg", form: "Kapsül", aciklama: "Progesteron desteği - gece" },
        { ad: "Duphaston 10 mg", form: "Tablet", aciklama: "Didrogesteron - günde 2" },
        { ad: "Utrogestan 200 mg", form: "Vajinal", aciklama: "Vajinal progesteron - gece" },
        { ad: "Gynazole Vajinal Krem", form: "Krem", aciklama: "Antifungal - 3 gün" },
        { ad: "Diflucan 150 mg", form: "Kapsül", aciklama: "Flukonazol - tek doz" },
        { ad: "Clomiphene 50 mg", form: "Tablet", aciklama: "Ovülasyon indüksiyonu" },
        { ad: "Magnezyum 375 mg", form: "Tablet", aciklama: "Gebelikte kramp - günde 1" },
        { ad: "Iron + Folic", form: "Tablet", aciklama: "Gebelik demiri - günde 1" },
        { ad: "Metformin 500 mg", form: "Tablet", aciklama: "PCOS tedavisi - yemekle" },
    ],
    "Pediatri": [
        { ad: "Parol Süspansiyon", form: "Şurup", aciklama: "Ateş/ağrı - 6 saatte 1" },
        { ad: "Nurofen Çocuk Şurubu", form: "Şurup", aciklama: "İbuprofen - 8 saatte 1" },
        { ad: "Augmentin Süspansiyon", form: "Şurup", aciklama: "Antibiyotik - 12 saatte 1" },
        { ad: "Zinnat Süspansiyon", form: "Şurup", aciklama: "Sefuroksim - 12 saatte 1" },
        { ad: "Zyrtec Şurup", form: "Şurup", aciklama: "Antihistaminik - günde 1" },
        { ad: "Ventolin Nebül", form: "Nebül", aciklama: "Bronkodilatatör - gerektiğinde" },
        { ad: "Pulmicort Nebül", form: "Nebül", aciklama: "Steroid - günde 2x" },
        { ad: "Novalgin Damla", form: "Damla", aciklama: "Ağrı/ateş - 6 saatte 1" },
        { ad: "D Vitamini 400 IU", form: "Damla", aciklama: "Profilaksi - günde 1" },
        { ad: "Probiyotik (Florajen)", form: "Saşe", aciklama: "Antibiyotik sonrası - günde 1" },
    ],
    "Nöroloji": [
        { ad: "Tegretol 200 mg", form: "Tablet", aciklama: "Karbamazepin - günde 2" },
        { ad: "Depakine 500 mg", form: "Tablet", aciklama: "Valproat - günde 2" },
        { ad: "Lyrica 75 mg", form: "Kapsül", aciklama: "Nöropatik ağrı - günde 2" },
        { ad: "Sumatriptan 50 mg", form: "Tablet", aciklama: "Migren atağı - gerektiğinde" },
        { ad: "Naproxen 550 mg", form: "Tablet", aciklama: "Gerilim başağrısı - gerektiğinde" },
        { ad: "Akineton 2 mg", form: "Tablet", aciklama: "Parkinson - günde 3" },
        { ad: "Madopar 125 mg", form: "Kapsül", aciklama: "Levodopa - günde 3" },
        { ad: "Sirdalud 4 mg", form: "Tablet", aciklama: "Kas spazmı - gerektiğinde" },
        { ad: "Lexapro 10 mg", form: "Tablet", aciklama: "Escitalopram - sabah 1" },
        { ad: "Risperdal 1 mg", form: "Tablet", aciklama: "Antipsikotik - gece 1" },
    ],
    "Genel Cerrahi": [
        { ad: "Cipro 500 mg", form: "Tablet", aciklama: "Antibiyotik - 12 saatte 1" },
        { ad: "Metronidazol 500 mg", form: "Tablet", aciklama: "Anaerop antibiyotik - günde 3" },
        { ad: "Pantoprazol 40 mg", form: "Tablet", aciklama: "PPI - sabah aç karnına" },
        { ad: "Tramadol 50 mg", form: "Kapsül", aciklama: "Ağrı kesici - gerektiğinde" },
        { ad: "Liyofit Probiyotik", form: "Saşe", aciklama: "Antibiyotik sonrası" },
        { ad: "Movicol Saşe", form: "Saşe", aciklama: "Laksatif - günde 1-3" },
        { ad: "Heparin 5000 IU", form: "Enjeksiyon", aciklama: "DVT profilaksisi SC" },
        { ad: "Ketoprofen 100 mg", form: "Tablet", aciklama: "NSAID - yemekle günde 2" },
        { ad: "Diflucan 150 mg", form: "Kapsül", aciklama: "Fungal enfeksiyon - tek doz" },
        { ad: "Klexane 40 mg", form: "Enjeksiyon", aciklama: "LMWH - günde 1 SC" },
    ],
    "Dermatoloji": [
        { ad: "Elocom Krem", form: "Krem", aciklama: "Steroid krem - günde 1" },
        { ad: "Protopic 0.1% Pomad", form: "Pomad", aciklama: "Kalsinörin inhibitörü - günde 2" },
        { ad: "Roaccutane 20 mg", form: "Kapsül", aciklama: "Isotretinoin - yemekle günde 1" },
        { ad: "Doxycycline 100 mg", form: "Kapsül", aciklama: "Akne antibiyotiği - günde 1" },
        { ad: "Lamisil Krem", form: "Krem", aciklama: "Antifungal - günde 1, 2 hafta" },
        { ad: "Zovirax Krem", form: "Krem", aciklama: "Herpes - günde 5x, 5 gün" },
        { ad: "Betametazon + Klotrimazol", form: "Krem", aciklama: "Steroid+antifungal kombine" },
        { ad: "Cetrizin 10 mg", form: "Tablet", aciklama: "Antihistaminik - gece 1" },
        { ad: "Methotrexate 2.5 mg", form: "Tablet", aciklama: "Psöriyazis - haftada 1" },
        { ad: "Benzoil Peroksit %5", form: "Jel", aciklama: "Akne jeli - gece 1" },
    ],
    "Psikiyatri": [
        { ad: "Prozac 20 mg", form: "Kapsül", aciklama: "Fluoksetin - sabah 1" },
        { ad: "Zoloft 50 mg", form: "Tablet", aciklama: "Sertralin - sabah 1" },
        { ad: "Xanax 0.5 mg", form: "Tablet", aciklama: "Alprazolam - gerektiğinde" },
        { ad: "Stilnox 10 mg", form: "Tablet", aciklama: "Uyku - yatmadan önce" },
        { ad: "Abilify 10 mg", form: "Tablet", aciklama: "Aripiprazol - sabah 1" },
        { ad: "Concerta 36 mg", form: "Tablet", aciklama: "DEHB - sabah 1" },
        { ad: "Cipralex 10 mg", form: "Tablet", aciklama: "Escitalopram - sabah 1" },
        { ad: "Remeron 15 mg", form: "Tablet", aciklama: "Mirtazapin - gece 1" },
        { ad: "Seroquel 25 mg", form: "Tablet", aciklama: "Ketiyapin - gece 1" },
        { ad: "Lamictal 25 mg", form: "Tablet", aciklama: "Lamotrijin - günde 2" },
    ],
    "Endokrinoloji": [
        { ad: "Metformin 1000 mg", form: "Tablet", aciklama: "Yemekle günde 2" },
        { ad: "Gliclazide 60 mg", form: "Tablet", aciklama: "Sulfonilüre - sabah yemekle" },
        { ad: "Humalog 100 IU/mL", form: "Kalem", aciklama: "Hızlı insülin - yemekle SC" },
        { ad: "Lantus 100 IU/mL", form: "Kalem", aciklama: "Bazal insülin - gece SC" },
        { ad: "Levothyroxine 100 mcg", form: "Tablet", aciklama: "Tiroid - aç karnına" },
        { ad: "Carbimzol 20 mg", form: "Tablet", aciklama: "Hipertiroidi - günde 2" },
        { ad: "Calcium 500 + D3", form: "Tablet", aciklama: "Osteoporoz desteği - günde 2" },
        { ad: "Victoza 1.2 mg", form: "Kalem", aciklama: "GLP-1 agonist - günde 1 SC" },
        { ad: "Januvia 100 mg", form: "Tablet", aciklama: "DPP-4 inhibitör - günde 1" },
        { ad: "Jardiance 10 mg", form: "Tablet", aciklama: "SGLT2 inhibitör - sabah" },
    ],
    "Gastroenteroloji": [
        { ad: "Nexium 40 mg", form: "Tablet", aciklama: "Esomeprazol - aç karnına" },
        { ad: "Zantac 300 mg", form: "Tablet", aciklama: "Ranitidin - gece 1" },
        { ad: "Motilium 10 mg", form: "Tablet", aciklama: "Prokinetik - yemekten önce 3x" },
        { ad: "Duphalac Şurup", form: "Şurup", aciklama: "Laktuloz - günde 1-2 kaşık" },
        { ad: "Salofalk 500 mg", form: "Tablet", aciklama: "Mesalazin - günde 3" },
        { ad: "Azathioprine 50 mg", form: "Tablet", aciklama: "İmmünsüpresif - günde 1-2" },
        { ad: "Ursofalk 250 mg", form: "Kapsül", aciklama: "UDCA - yemekle günde 3" },
        { ad: "Debridat 100 mg", form: "Tablet", aciklama: "Spazmolitik - günde 3" },
        { ad: "Enterol 250 mg", form: "Kapsül", aciklama: "Probiyotik - günde 2" },
        { ad: "Smecta Saşe", form: "Saşe", aciklama: "İshal - günde 3 saşe" },
    ],
    "Nefroloji": [
        { ad: "Furosemid 40 mg", form: "Tablet", aciklama: "Diüretik - sabah 1" },
        { ad: "Spironolakton 25 mg", form: "Tablet", aciklama: "K+ tutucu diüretik - günde 1" },
        { ad: "Ramipril 5 mg", form: "Tablet", aciklama: "ACE inhibitör - günde 1" },
        { ad: "Sevelamer 800 mg", form: "Tablet", aciklama: "Fosfat bağlayıcı - yemekle" },
        { ad: "Erythropoetin 4000 IU", form: "Enjeksiyon", aciklama: "Haftada 3 SC" },
        { ad: "Calcium Acetate 667 mg", form: "Tablet", aciklama: "Fosfat bağlayıcı - yemekle" },
        { ad: "Allopurinol 300 mg", form: "Tablet", aciklama: "Ürik asit - günde 1" },
        { ad: "Bikarbonat 500 mg", form: "Tablet", aciklama: "Asidoz tedavisi - günde 3" },
        { ad: "Paricalcitol 1 mcg", form: "Kapsül", aciklama: "Aktif D vitamini - günde 1" },
        { ad: "Kayexalate Toz", form: "Toz", aciklama: "Hiperkalemi - günde 3-4x" },
    ],
    "Onkoloji": [
        { ad: "Zofran 8 mg", form: "Tablet", aciklama: "Bulantı önleyici - günde 2" },
        { ad: "Dexamethasone 8 mg", form: "Tablet", aciklama: "Steroid - sabah" },
        { ad: "Neupogen 300 mcg", form: "Enjeksiyon", aciklama: "G-CSF - SC günde 1" },
        { ad: "Zometa 4 mg", form: "IV", aciklama: "Bifosfonat - 3-4 haftada 1" },
        { ad: "Tamoxifen 20 mg", form: "Tablet", aciklama: "Hormon tedavisi - günde 1" },
        { ad: "Letrozole 2.5 mg", form: "Tablet", aciklama: "Aromataz inhibitör - günde 1" },
        { ad: "Gleevec 400 mg", form: "Tablet", aciklama: "İmatinib - yemekle günde 1" },
        { ad: "Xeloda 500 mg", form: "Tablet", aciklama: "Kapesitabin - yemekle 2x günde" },
        { ad: "Morphine SR 10 mg", form: "Tablet", aciklama: "Ağrı - 12 saatte 1" },
        { ad: "Loperamide 2 mg", form: "Kapsül", aciklama: "Kemo ishal - gerektiğinde" },
    ],
    "Fizik Tedavi": [
        { ad: "Voltaren 75 mg", form: "Tablet", aciklama: "NSAID - yemekle günde 2" },
        { ad: "Muscoril 4 mg", form: "Kapsül", aciklama: "Kas gevşetici - günde 3" },
        { ad: "Neurontin 300 mg", form: "Kapsül", aciklama: "Nöropatik ağrı - günde 3" },
        { ad: "Lyrica 75 mg", form: "Kapsül", aciklama: "Fibromiyalji - günde 2" },
        { ad: "Calcium + D3", form: "Tablet", aciklama: "Kemik güçlendirme - günde 1" },
        { ad: "Glucosamine 1500 mg", form: "Tablet", aciklama: "Eklem desteği - günde 1" },
        { ad: "Chondroitin 1200 mg", form: "Tablet", aciklama: "Kıkırdak desteği - günde 1" },
        { ad: "Tramadol 50 mg", form: "Kapsül", aciklama: "Ağrı - gerektiğinde" },
        { ad: "Tolperisone 150 mg", form: "Tablet", aciklama: "Kas gevşetici - günde 3" },
        { ad: "Voltaren Jel %1", form: "Jel", aciklama: "Lokal uygulama - günde 3" },
    ],
    "Enfeksiyon": [
        { ad: "Amoxicillin 500 mg", form: "Kapsül", aciklama: "Antibiyotik - günde 3" },
        { ad: "Augmentin 1000 mg", form: "Tablet", aciklama: "Amoks+Klav - 12 saatte 1" },
        { ad: "Cipro 500 mg", form: "Tablet", aciklama: "Florokinolon - 12 saatte 1" },
        { ad: "Doxycycline 100 mg", form: "Kapsül", aciklama: "Tetrasiklin - 12 saatte 1" },
        { ad: "Klaritromisin 500 mg", form: "Tablet", aciklama: "Makrolid - 12 saatte 1" },
        { ad: "Metronidazol 500 mg", form: "Tablet", aciklama: "Anaerop - günde 3" },
        { ad: "Diflucan 150 mg", form: "Kapsül", aciklama: "Antifungal - tek doz" },
        { ad: "Valacyclovir 500 mg", form: "Tablet", aciklama: "Antiviral - günde 2" },
        { ad: "Tamiflu 75 mg", form: "Kapsül", aciklama: "Influenza - günde 2, 5 gün" },
        { ad: "Bactrim 960 mg", form: "Tablet", aciklama: "Trimetoprim+Sulfametoksazol" },
    ],
    "Üroloji": [
        { ad: "Flomax 0.4 mg", form: "Kapsül", aciklama: "Alfa bloker - akşam yemekle" },
        { ad: "Proscar 5 mg", form: "Tablet", aciklama: "5-alfa redüktaz - günde 1" },
        { ad: "Cialis 5 mg", form: "Tablet", aciklama: "PDE5 inhibitör - günde 1" },
        { ad: "Ditropan 5 mg", form: "Tablet", aciklama: "Aşırı aktif mesane - günde 2" },
        { ad: "Cipro 500 mg", form: "Tablet", aciklama: "İdrar yolu enfeksiyonu - 7 gün" },
        { ad: "Furosemid 40 mg", form: "Tablet", aciklama: "Diüretik - sabah 1" },
        { ad: "Potasyum Sitrat 1080 mg", form: "Tablet", aciklama: "Taş önleyici - günde 3" },
        { ad: "Dutasteride 0.5 mg", form: "Kapsül", aciklama: "BPH tedavisi - günde 1" },
        { ad: "Solifenacin 5 mg", form: "Tablet", aciklama: "Antimuskarinik - günde 1" },
        { ad: "Tolterodine 4 mg", form: "Kapsül", aciklama: "İdrar kaçırma - günde 1" },
    ],
    "Göğüs Hastalıkları": [
        { ad: "Ventolin İnhaler", form: "İnhaler", aciklama: "Salbutamol - gerektiğinde 2 puf" },
        { ad: "Symbicort 160/4.5 mcg", form: "İnhaler", aciklama: "Bud+Formoterol - günde 2x2" },
        { ad: "Spiriva 18 mcg", form: "İnhaler", aciklama: "Tiotropium - sabah 1 puf" },
        { ad: "Singulair 10 mg", form: "Tablet", aciklama: "Lökotrien antag. - gece 1" },
        { ad: "Pulmicort 200 mcg", form: "İnhaler", aciklama: "Steroid - günde 2x1" },
        { ad: "Augmentin 1000 mg", form: "Tablet", aciklama: "Pnömoni - 12 saatte 1" },
        { ad: "Erdostein 300 mg", form: "Kapsül", aciklama: "Mukolitik - günde 2" },
        { ad: "Codein Fosfat 30 mg", form: "Tablet", aciklama: "Öksürük - gerektiğinde" },
        { ad: "Prednisolone 20 mg", form: "Tablet", aciklama: "KOAH atağı - azaltarak kes" },
        { ad: "Azitromisin 500 mg", form: "Tablet", aciklama: "Atipik pnömoni - günde 1" },
    ],
    "Acil Servis": [
        { ad: "Parol 500 mg", form: "Tablet", aciklama: "Parasetamol - 6 saatte 1" },
        { ad: "Nurofen 400 mg", form: "Tablet", aciklama: "İbuprofen - 8 saatte 1" },
        { ad: "Cipro 500 mg", form: "Tablet", aciklama: "Antibiyotik - 12 saatte 1" },
        { ad: "Pantoprazol 40 mg", form: "Tablet", aciklama: "PPI - aç karnına" },
        { ad: "Metoklopramid 10 mg", form: "Tablet", aciklama: "Bulantı - günde 3" },
        { ad: "Buscopan 10 mg", form: "Tablet", aciklama: "Spazmolitik - günde 3" },
        { ad: "Coraspin 100 mg", form: "Tablet", aciklama: "Antiplatelet - günde 1" },
        { ad: "Ventolin İnhaler", form: "İnhaler", aciklama: "Bronkospazm - 2-4 puf" },
        { ad: "Diazepam 5 mg", form: "Tablet", aciklama: "Anksiyete/spazmı - gerektiğinde" },
        { ad: "Tramadol 50 mg", form: "Kapsül", aciklama: "Ağrı - gerektiğinde" },
    ],
};

// Poliklinik bulunamazsa genel ilaçlar
export const GENEL_ILACLAR = [
    { ad: "Parol 500 mg", form: "Tablet", aciklama: "Ağrı/ateş - 6 saatte 1" },
    { ad: "Nurofen 400 mg", form: "Tablet", aciklama: "NSAID - 8 saatte 1" },
    { ad: "Amoxicillin 500 mg", form: "Kapsül", aciklama: "Antibiyotik - günde 3" },
    { ad: "Omeprazol 20 mg", form: "Kapsül", aciklama: "Mide koruyucu - aç karnına" },
    { ad: "Metronidazol 500 mg", form: "Tablet", aciklama: "Enfeksiyon - günde 3" },
];

export const poliklinikIlaclariGetir = (poliklinik) =>
    POLIKLINIK_ILACLARI[poliklinik] || GENEL_ILACLAR;