server.port=8081
server.address=0.0.0.0
spring.datasource.url=jdbc:postgresql://192.168.234.236:5432/HBYS
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ============ LOGGING ============
logging.level.root=INFO

# Kendi paketimiz daha detayl? olsun
logging.level.com.hastane.hastane_backend=DEBUG

# Spring Security loglar? çok uzat?r, gerekirse açars?n
logging.level.org.springframework.security=WARN

# Hibernate SQL görmek istersen aç
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Log format? (k?sa + okunur)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n